- name: isntall redis repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    state: installed
    disable_gpg_check: true

- name: enable redis 6
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

- name: install redis server
  ansible.builtin.yum:
    name: redis
    state: installed

- name: replacing 127.0.0.1
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: starting service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes