- name: configurimng repos
  ansible.builtin.shell: curl -s {{ item }} |  bash
  loop:
    - https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
    - https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

- name: install rabbitmq & erlang
  ansible.builtin.yum:
    name:
      - erlang
      - rabbitmq-server
    state: installed

- name: starting service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: adding user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator

