- name: to get nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install noodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed
- name: adding user
  ansible.builtin.user:
    name: roboshop

- name: Removing directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: creating directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: downloading and extracting frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: installing nodejs dependencies
  community.general.npm:
    path: /app
    state: latest

- name: copy file for config
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: starting service
  ansible.builtin.systemd:
    name: catalogue
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: copy file for config
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.devops-b70.online
    file: "/app/schema/catalogue.js"
    idempotent: yes



