- name: adding user
  ansible.builtin.user:
    name: roboshop

- name: Removing directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: creating directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: downloading and extracting {{component}} content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes